FROM rabbitmq:3-management

# Copy the delayed message exchange plugin
COPY backend/server/rabbitmq-setup/*.ez /plugins/

# Setup logging
RUN mkdir -p /etc/rabbitmq/conf.d
RUN chown -R rabbitmq:rabbitmq /etc/rabbitmq/conf.d
COPY backend/server/rabbitmq-setup/20-logging.conf /etc/rabbitmq/conf.d

# Enable the delayed message exchange plugin
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange

# Set the plugins directory
ENV RABBITMQ_PLUGINS_DIR="/plugins"
